/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResourceCategory = IDL.Variant({
  'taxes' : IDL.Null,
  'saving' : IDL.Null,
  'investing' : IDL.Null,
  'loans' : IDL.Null,
  'credit' : IDL.Null,
  'budgeting' : IDL.Null,
  'retirement' : IDL.Null,
});
export const Resource = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : ResourceCategory,
});

export const idlService = IDL.Service({
  'addResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ResourceCategory],
      [],
      [],
    ),
  'deleteResource' : IDL.Func([IDL.Text], [], []),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getResource' : IDL.Func([IDL.Text], [Resource], ['query']),
  'getResourcesByCategory' : IDL.Func(
      [ResourceCategory],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'updateResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ResourceCategory],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResourceCategory = IDL.Variant({
    'taxes' : IDL.Null,
    'saving' : IDL.Null,
    'investing' : IDL.Null,
    'loans' : IDL.Null,
    'credit' : IDL.Null,
    'budgeting' : IDL.Null,
    'retirement' : IDL.Null,
  });
  const Resource = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : ResourceCategory,
  });
  
  return IDL.Service({
    'addResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ResourceCategory],
        [],
        [],
      ),
    'deleteResource' : IDL.Func([IDL.Text], [], []),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getResource' : IDL.Func([IDL.Text], [Resource], ['query']),
    'getResourcesByCategory' : IDL.Func(
        [ResourceCategory],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'updateResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ResourceCategory],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };