/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Resource {
  'url' : string,
  'title' : string,
  'description' : string,
  'category' : ResourceCategory,
}
export type ResourceCategory = { 'taxes' : null } |
  { 'saving' : null } |
  { 'investing' : null } |
  { 'loans' : null } |
  { 'credit' : null } |
  { 'budgeting' : null } |
  { 'retirement' : null };
export interface _SERVICE {
  'addResource' : ActorMethod<
    [string, string, string, string, ResourceCategory],
    undefined
  >,
  'deleteResource' : ActorMethod<[string], undefined>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getResource' : ActorMethod<[string], Resource>,
  'getResourcesByCategory' : ActorMethod<[ResourceCategory], Array<Resource>>,
  'updateResource' : ActorMethod<
    [string, string, string, string, ResourceCategory],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];