/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Resource {
    url: string;
    title: string;
    description: string;
    category: ResourceCategory;
}
export enum ResourceCategory {
    taxes = "taxes",
    saving = "saving",
    investing = "investing",
    loans = "loans",
    credit = "credit",
    budgeting = "budgeting",
    retirement = "retirement"
}
export interface backendInterface {
    addResource(id: string, title: string, description: string, url: string, category: ResourceCategory): Promise<void>;
    deleteResource(id: string): Promise<void>;
    getAllResources(): Promise<Array<Resource>>;
    getResource(id: string): Promise<Resource>;
    getResourcesByCategory(category: ResourceCategory): Promise<Array<Resource>>;
    updateResource(id: string, title: string, description: string, url: string, category: ResourceCategory): Promise<void>;
}
import type { Resource as _Resource, ResourceCategory as _ResourceCategory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addResource(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ResourceCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(arg0, arg1, arg2, arg3, to_candid_ResourceCategory_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(arg0, arg1, arg2, arg3, to_candid_ResourceCategory_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteResource(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResource(arg0);
            return result;
        }
    }
    async getAllResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResources();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResources();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResource(arg0: string): Promise<Resource> {
        if (this.processError) {
            try {
                const result = await this.actor.getResource(arg0);
                return from_candid_Resource_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResource(arg0);
            return from_candid_Resource_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourcesByCategory(arg0: ResourceCategory): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesByCategory(to_candid_ResourceCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesByCategory(to_candid_ResourceCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateResource(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ResourceCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResource(arg0, arg1, arg2, arg3, to_candid_ResourceCategory_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResource(arg0, arg1, arg2, arg3, to_candid_ResourceCategory_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_ResourceCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceCategory): ResourceCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    title: string;
    description: string;
    category: _ResourceCategory;
}): {
    url: string;
    title: string;
    description: string;
    category: ResourceCategory;
} {
    return {
        url: value.url,
        title: value.title,
        description: value.description,
        category: from_candid_ResourceCategory_n6(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxes: null;
} | {
    saving: null;
} | {
    investing: null;
} | {
    loans: null;
} | {
    credit: null;
} | {
    budgeting: null;
} | {
    retirement: null;
}): ResourceCategory {
    return "taxes" in value ? ResourceCategory.taxes : "saving" in value ? ResourceCategory.saving : "investing" in value ? ResourceCategory.investing : "loans" in value ? ResourceCategory.loans : "credit" in value ? ResourceCategory.credit : "budgeting" in value ? ResourceCategory.budgeting : "retirement" in value ? ResourceCategory.retirement : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ResourceCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): _ResourceCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): {
    taxes: null;
} | {
    saving: null;
} | {
    investing: null;
} | {
    loans: null;
} | {
    credit: null;
} | {
    budgeting: null;
} | {
    retirement: null;
} {
    return value == ResourceCategory.taxes ? {
        taxes: null
    } : value == ResourceCategory.saving ? {
        saving: null
    } : value == ResourceCategory.investing ? {
        investing: null
    } : value == ResourceCategory.loans ? {
        loans: null
    } : value == ResourceCategory.credit ? {
        credit: null
    } : value == ResourceCategory.budgeting ? {
        budgeting: null
    } : value == ResourceCategory.retirement ? {
        retirement: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
